name: Deploy Bicep file
on: [push]
permissions:
      id-token: write
      contents: read
      
jobs: 
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Checkout CARML
      run: |
          git config --global url.https://github.com/.insteadOf git://github.com/
          git clone https://github.com/Azure/ResourceModules.git
          ls

  build-and-deploy:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout Code
      uses: actions/checkout@main

    - name: Log into Azure
      uses: azure/login@v1
      with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Check out the CARML repo
      uses: actions/checkout@v3
      with:
        repository: Azure/ResourceModules
        path: ./ResourceModules
        
    - name: Deploy Bicep file
      uses: azure/arm-deploy@v1
      with:
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        resourceGroupName: ${{ secrets.AZURE_RG }}
        template: ./deploy/main.bicep
        parameters: ./deploy/parameters.bicepparam
        failOnStdErr: false
